kind: Pod
apiVersion: v1
metadata:
  name: jspiders
spec:
  containers:
    - name: sample1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hi everyone; sleep 5; done"]
  restartPolicy: Never         # Defaults to Always

