apiVersion: v1
kind: ReplicationController
metadata:
  name: flipkart
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: signup
      labels:
        app: nginx
    spec:
      containers:
        - name: sigupemail
          image: nginx
          ports:
            - containerPort: 80
